export {default as PlayCircle} from './svgs/play-circle.svg?raw'
export {default as Filter} from './svgs/filter.svg?raw'
export {default as Photo} from './svgs/photo.svg?raw'
export {default as Gif} from './svgs/gif.svg?raw'
export {default as ChevronLeft} from './svgs/cheveron-left.svg?raw'
export {default as ChevronRight} from './svgs/cheveron-right.svg?raw'
export {default as Pause} from './svgs/pause.svg?raw'
