name: 'Shared Steps'
description: 'Runs checkout, setup, and custom logs'


inputs:
  DENO_VERSION:
    default: '2.9'
  FFMPEG_VERSION:
    default: '8.1'
  DENO_DIR:
    default: 'deno_dependency_cache'

runs:
  using: 'composite'
  steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Deno
      uses: denoland/setup-deno@v2
      with:
        deno-version: "${{ inputs.DENO_VERSION }}"

    - name: Setup FFmpeg
      uses: AnimMouse/setup-ffmpeg@v1
      with:
        version: "${{ inputs.FFMPEG_VERSION }}"

    - name: Cache Deno dependencies 
      uses: actions/cache@v6
      with:
        path: ${{ inputs.DENO_DIR }}
        key: "deno:${{ inputs.DENO_VERSION }}:deno.lock:${{ hashFiles('deno.lock') }}"

    - name: Install deno dependencies
      run: deno install
      shell: bash
