import './seed_migration.ts'
import './migration_v2.ts'
import './migration_v3.ts'
import './migration_v4.ts'
import './migration_v5.ts'
import './migration_v6.ts'
import './migration_v7.ts'
import './migration_v8.ts'
import './migration_v9.ts'
import './migration_v10.ts'
import './migration_v11.ts'
import './migration_v12.ts'

export { migrations } from './registry.ts'
