name: Continuous Releases


permissions:
  contents: read
on:
  push:
    tags: ["*"]

defaults:
  run:
    working-directory: '.'


jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: canary

      - name: Setup FFMPEG
        uses: FedericoCarboni/setup-ffmpeg@v3
        id: setup-ffmpeg
        with:
          ffmpeg-version: 7.0.1

      - name: "Install dependencies"
        run: deno install --allow-scripts

      - name: "Build @forager/web Dependency"
        run: deno task --cwd packages/web build

      - name: Test
        run: deno task --cwd packages/cli test

      - name: Compile
        run: deno task compile

  # TODO uncomment publishing @forager/cli once we have proper support for raw byte imports in jsr https://github.com/denoland/deno/issues/29904
  # publish:
  #   runs-on: ubuntu-latest
  #   needs: test

  #   permissions:
  #     contents: read
  #     id-token: write

  #   steps:
  #     - name: Setup repo
  #       uses: actions/checkout@v4

  #     - name: Setup Deno
  #       uses: denoland/setup-deno@v2
  #       with:
  #         deno-version: canary

  #     - name: Publish package
  #       if: github.ref == 'refs/heads/main'
  #       run: deno publish
