name: Web CI
description: "Builds @forager/web"


permissions:
  contents: read
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

defaults:
  run:
    working-directory: './packages/web'


jobs:
  test:
    strategy:
      matrix:
        # windows & mac is overkill for web tests, which essentially just builds the sveltekit project and type checks it
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: checkout repository
        uses: actions/checkout@v6

      - name: setup
        uses: './.github/actions/shared_setup'

      # - name: Lint
      # run: deno task lint

      # - name: Typecheck
      # run: deno task check

      - name: Build
        run: deno task build

  # TODO uncomment publishing @forager/web once we have proper support for raw byte imports in jsr https://github.com/denoland/deno/issues/29904
  # publish:
  #   runs-on: ubuntu-latest
  #   needs: test

  #   steps:
      - name: checkout repository
        uses: actions/checkout@v6

      - name: setup
        uses: './.github/actions/shared_setup'

  #     - name: Build
  #       run: deno task build

  #     - name: Publish package
  #       if: github.ref == 'refs/heads/main'
  #       run: deno publish --allow-slow-types
  #       working-directory: ./packages/web/adapter/lib
